spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/jd2"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/jd2"
server:
  port: 8080

---

jwt:
  secret: qwepuisdhfaksdjflsdfn12321___**
  expiration: 60000